# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Load the CircleCI Windows orb
orbs:
  newman: circleci/windows@5.0.0


jobs:
  run-all-tests:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: "Restore project dependencies"
          command: dotnet.exe restore
      - run:
          name: "Run tests"
          command: dotnet.exe test          
workflows:
  run-rest-assured-net-tests:
    jobs:
      - run-all-tests